# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-13 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('content', models.TextField(blank=True, default='', max_length=5000, null=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442')),
                ('ord', models.IntegerField(default=0, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043a\u043e\u0432\u044b\u0439 \u043d\u043e\u043c\u0435\u0440')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0442\u044c\u044f',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u0438',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0411\u043b\u043e\u043a',
                'verbose_name_plural': '\u0411\u043b\u043e\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('description', models.TextField(blank=True, default='', max_length=5000, null=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442')),
                ('image', models.ImageField(default='', upload_to='Img/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('block', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='db.Block', verbose_name='\u0411\u043b\u043e\u043a')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430',
                'verbose_name_plural': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0432\u0445\u043e\u0434\u0430')),
                ('remote_adr', models.CharField(default='', max_length=100, verbose_name='IP')),
                ('city', models.CharField(default='', max_length=100, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('region', models.CharField(default='', max_length=100, verbose_name='\u041e\u0431\u043b\u0430\u0441\u0442\u044c')),
                ('time_zone', models.CharField(default='', max_length=100, verbose_name='\u0412\u0440\u0435\u043c\u0435\u043d\u043d\u0430\u044f \u0437\u043e\u043d\u0430')),
                ('refer', models.TextField(default='', max_length=2000, verbose_name='\u041b\u0438\u043d\u043a')),
                ('browser', models.CharField(default='', max_length=200, verbose_name='\u0411\u0440\u0430\u0443\u0437\u0435\u0440')),
                ('version', models.CharField(default='', max_length=200, verbose_name='\u0412\u0435\u0440\u0441\u0438\u044f \u0431\u0440\u0430\u0443\u0437\u0435\u0440\u0430')),
                ('device', models.CharField(default='', max_length=200, verbose_name='\u0423\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u043e\u0432\u043e')),
                ('os', models.CharField(default='', max_length=200, verbose_name='\u041e\u0421')),
                ('source', models.CharField(default='', max_length=200, verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0441\u0435\u0442\u0438\u0442\u0435\u043b\u044c',
                'verbose_name_plural': '\u041f\u043e\u0441\u0435\u0442\u0438\u0442\u0435\u043b\u0438',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='block',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='db.Block', verbose_name='\u0411\u043b\u043e\u043a'),
        ),
    ]
