# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-24 09:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('content', models.TextField(blank=True, default='', max_length=5000, null=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442')),
                ('block', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='\u0411\u043b\u043e\u043a')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0442\u044c\u044f',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u0438',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('description', models.TextField(blank=True, default='', max_length=5000, null=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442')),
                ('image', models.ImageField(default='', upload_to='Img/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('block', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='\u0411\u043b\u043e\u043a')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430',
                'verbose_name_plural': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2017, 4, 24, 14, 59, 37, 553000), verbose_name='\u0414\u0430\u0442\u0430 \u0432\u0445\u043e\u0434\u0430')),
                ('remote_adr', models.CharField(default='', max_length=100, verbose_name='IP')),
                ('remote_host', models.TextField(default='', max_length=1000, verbose_name='Host')),
                ('refer', models.TextField(default='', max_length=2000, verbose_name='Refer')),
                ('user_agent', models.TextField(default='', max_length=2000, verbose_name='\u0411\u0440\u0430\u0443\u0437\u0435\u0440')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0441\u0435\u0442\u0438\u0442\u0435\u043b\u044c',
                'verbose_name_plural': '\u041f\u043e\u0441\u0435\u0442\u0438\u0442\u0435\u043b\u0438',
            },
        ),
    ]
