# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-24 10:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='block',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='db.Block'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='block',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='db.Block'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 24, 15, 16, 15, 844000), verbose_name='\u0414\u0430\u0442\u0430 \u0432\u0445\u043e\u0434\u0430'),
        ),
    ]
