# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-24 10:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20170424_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': '\u0411\u043b\u043e\u043a', 'verbose_name_plural': '\u0411\u043b\u043e\u043a\u0438'},
        ),
        migrations.AddField(
            model_name='article',
            name='ord',
            field=models.IntegerField(default=0, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043a\u043e\u0432\u044b\u0439 \u043d\u043e\u043c\u0435\u0440'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 24, 15, 23, 46, 847000), verbose_name='\u0414\u0430\u0442\u0430 \u0432\u0445\u043e\u0434\u0430'),
        ),
    ]
