# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-25 06:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20170424_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='remote_host',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='visitor',
            name='browser',
            field=models.TextField(default='', max_length=200, verbose_name='\u0411\u0440\u0430\u0443\u0437\u0435\u0440'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='device',
            field=models.TextField(default='', max_length=200, verbose_name='\u0423\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u043e\u0432\u043e'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='os',
            field=models.TextField(default='', max_length=200, verbose_name='\u041e\u0421'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='region',
            field=models.CharField(default='', max_length=100, verbose_name='\u041e\u0431\u043b\u0430\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='time_zone',
            field=models.CharField(default='', max_length=100, verbose_name='\u0412\u0440\u0435\u043c\u0435\u043d\u043d\u0430\u044f \u0437\u043e\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='version',
            field=models.TextField(default='', max_length=200, verbose_name='\u0412\u0435\u0440\u0441\u0438\u044f \u0431\u0440\u0430\u0443\u0437\u0435\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='article',
            name='block',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='db.Block', verbose_name='\u0411\u043b\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='block',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='db.Block', verbose_name='\u0411\u043b\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='refer',
            field=models.TextField(default='', max_length=2000, verbose_name='\u041b\u0438\u043d\u043a'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 25, 11, 21, 34, 873000), verbose_name='\u0414\u0430\u0442\u0430 \u0432\u0445\u043e\u0434\u0430'),
        ),
    ]
