# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-25 07:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20170425_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='source',
            field=models.CharField(default='', max_length=200, verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='browser',
            field=models.CharField(default='', max_length=200, verbose_name='\u0411\u0440\u0430\u0443\u0437\u0435\u0440'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='device',
            field=models.CharField(default='', max_length=200, verbose_name='\u0423\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u043e\u0432\u043e'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='os',
            field=models.CharField(default='', max_length=200, verbose_name='\u041e\u0421'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 25, 12, 12, 14, 239000), verbose_name='\u0414\u0430\u0442\u0430 \u0432\u0445\u043e\u0434\u0430'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='version',
            field=models.CharField(default='', max_length=200, verbose_name='\u0412\u0435\u0440\u0441\u0438\u044f \u0431\u0440\u0430\u0443\u0437\u0435\u0440\u0430'),
        ),
    ]
