# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-13 08:57
from __future__ import unicode_literals

import app.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=191, verbose_name='\u0424\u0418\u041e')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
            ],
            options={
                'ordering': ('-id',),
                'verbose_name': '\u041f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c',
                'verbose_name_plural': '\u041f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u0438',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('price', models.PositiveIntegerField(verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c')),
            ],
            options={
                'verbose_name': '\u0422\u043e\u0432\u0430\u0440',
                'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 5, 13, 8, 57, 40, 491000, tzinfo=utc), verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u0438\u044f \u0437\u0430\u044f\u0432\u043a\u0438')),
                ('type', models.CharField(blank=True, choices=[('try_subscribe', '\u041f\u043e\u0434\u043f\u0438\u0441\u043a\u0430, \u043d\u0435 \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0434\u0435\u043d\u0430'), ('subscribe', '\u041f\u043e\u0434\u043f\u0438\u0441\u043a\u0430, \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0430'), ('unsubscribe', '\u041f\u043e\u0434\u043f\u0438\u0441\u043a\u0430, \u043e\u0442\u043c\u0435\u043d\u0435\u043d\u0430'), ('purchase', '\u041f\u043e\u043a\u0443\u043f\u043a\u0430')], default='', max_length=50, null=True, verbose_name='\u0422\u0438\u043f \u0437\u0430\u044f\u0432\u043a\u0438')),
                ('auth_code', models.CharField(default='0', max_length=50, verbose_name='\u041a\u043e\u0434 \u0430\u0432\u0442\u043e\u0440\u0438\u0437\u0430\u0446\u0438\u0438')),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Customer', verbose_name='\u041f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u044f\u0432\u043a\u0430',
                'verbose_name_plural': '\u0417\u0430\u044f\u0432\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('shop_id', models.PositiveIntegerField(default=170735, verbose_name='ID \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u0430')),
                ('scid', models.PositiveIntegerField(default=721947, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0432\u0438\u0442\u0440\u0438\u043d\u044b')),
                ('customer_number', models.CharField(default=app.models.get_default_as_uuid, max_length=64, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043f\u043b\u0430\u0442\u0435\u043b\u044c\u0449\u0438\u043a\u0430')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='\u0421\u0443\u043c\u043c\u0430 \u0437\u0430\u043a\u0430\u0437\u0430')),
                ('payment_type', models.CharField(choices=[('PC', '\u041a\u043e\u0448\u0435\u043b\u0435\u043a \u042f\u043d\u0434\u0435\u043a\u0441.\u0414\u0435\u043d\u044c\u0433\u0438'), ('AC', '\u0411\u0430\u043d\u043a\u043e\u0432\u0441\u043a\u0430\u044f \u043a\u0430\u0440\u0442\u0430'), ('GP', '\u041d\u0430\u043b\u0438\u0447\u043d\u044b\u043c\u0438 \u0447\u0435\u0440\u0435\u0437 \u043a\u0430\u0441\u0441\u044b \u0438 \u0442\u0435\u0440\u043c\u0438\u043d\u0430\u043b\u044b'), ('MC', '\u0421\u0447\u0435\u0442 \u043c\u043e\u0431\u0438\u043b\u044c\u043d\u043e\u0433\u043e \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430'), ('WM', '\u041a\u043e\u0448\u0435\u043b\u0435\u043a WebMoney'), ('SB', '\u0421\u0431\u0435\u0440\u0431\u0430\u043d\u043a: \u043e\u043f\u043b\u0430\u0442\u0430 \u043f\u043e SMS \u0438\u043b\u0438 \u0421\u0431\u0435\u0440\u0431\u0430\u043d\u043a \u041e\u043d\u043b\u0430\u0439\u043d'), ('AB', '\u0410\u043b\u044c\u0444\u0430-\u041a\u043b\u0438\u043a'), ('MA', 'MasterPass'), ('PB', '\u0418\u043d\u0442\u0435\u0440\u043d\u0435\u0442-\u0431\u0430\u043d\u043a \u041f\u0440\u043e\u043c\u0441\u0432\u044f\u0437\u044c\u0431\u0430\u043d\u043a\u0430'), ('QW', 'QIWI Wallet'), ('QP', '\u0414\u043e\u0432\u0435\u0440\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439 \u043f\u043b\u0430\u0442\u0435\u0436 (\u041a\u0443\u043f\u043f\u0438.\u0440\u0443)'), ('DF', '\u041d\u0435 \u0432\u044b\u0431\u0440\u0430\u043d')], default='DF', max_length=2, verbose_name='\u0421\u043f\u043e\u0441\u043e\u0431 \u043f\u043b\u0430\u0442\u0435\u0436\u0430')),
                ('order_number', models.CharField(default=app.models.get_default_as_uuid, max_length=64, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0437\u0430\u043a\u0430\u0437\u0430')),
                ('cps_email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email \u043f\u043b\u0430\u0442\u0435\u043b\u044c\u0449\u0438\u043a\u0430')),
                ('cps_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d \u043f\u043b\u0430\u0442\u0435\u043b\u044c\u0449\u0438\u043a\u0430')),
                ('success_url', models.URLField(default=b'https://made-fashion.ru/kassa/success/', verbose_name='URL \u0443\u0441\u043f\u0435\u0448\u043d\u043e\u0439 \u043e\u043f\u043b\u0430\u0442\u044b')),
                ('fail_url', models.URLField(default=b'https://made-fashion.ru/kassa/fail/', verbose_name='URL \u043d\u0435\u0443\u0441\u043f\u0435\u0448\u043d\u043e\u0439 \u043e\u043f\u043b\u0430\u0442\u044b')),
                ('status', models.CharField(choices=[('processed', '\u0421\u0447\u0435\u0442 \u0432\u044b\u0441\u0442\u0430\u0432\u043b\u0435\u043d'), ('checked_s', '\u041f\u0440\u043e\u0432\u0435\u0440\u043a\u0430 \u043f\u0440\u043e\u0439\u0434\u0435\u043d\u0430'), ('checked_f', '\u041f\u0440\u043e\u0432\u0435\u0440\u043a\u0430 \u043d\u0435 \u043f\u0440\u043e\u0439\u0434\u0435\u043d\u0430  '), ('success', '\u0421\u0447\u0435\u0442 \u043e\u043f\u043b\u0430\u0447\u0435\u043d'), ('fail', '\u0421\u0447\u0435\u0442 \u043d\u0435 \u043e\u043f\u043b\u0430\u0447\u0435\u043d')], default='processed', max_length=16, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('invoice_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u0438 \u043e\u043f\u0435\u0440\u0430\u0442\u043e\u0440\u0430')),
                ('shop_amount', models.DecimalField(blank=True, decimal_places=2, help_text='\u0417\u0430 \u0432\u044b\u0447\u0435\u0442\u043e\u043c \u043f\u0440\u043e\u0446\u0435\u043d\u0442\u0430 \u043e\u043f\u0435\u0440\u0430\u0442\u043e\u0440\u0430', max_digits=15, null=True, verbose_name='\u0421\u0443\u043c\u043c\u0430 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u043d\u0430\u044f \u043d\u0430 \u0440/\u0441')),
                ('order_currency', models.PositiveIntegerField(choices=[(643, '\u0420\u0443\u0431\u043b\u0438'), (10643, '\u0422\u0435\u0441\u0442\u043e\u0432\u0430\u044f \u0432\u0430\u043b\u044e\u0442\u0430')], default=643, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430')),
                ('shop_currency', models.PositiveIntegerField(blank=True, choices=[(643, '\u0420\u0443\u0431\u043b\u0438'), (10643, '\u0422\u0435\u0441\u0442\u043e\u0432\u0430\u044f \u0432\u0430\u043b\u044e\u0442\u0430')], default=643, null=True, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u043d\u0430\u044f \u043d\u0430 \u0440/\u0441')),
                ('performed_datetime', models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 13, 8, 57, 40, 490000, tzinfo=utc), null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0435 \u0437\u0430\u043f\u0440\u043e\u0441\u0430')),
                ('ym_merchant_receipt', models.TextField(blank=True, max_length=2000, null=True, verbose_name='\u041a\u043e\u0440\u0437\u0438\u043d\u0430')),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Customer', verbose_name='\u041f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c')),
                ('good_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Goods', verbose_name='\u0422\u043e\u0432\u0430\u0440')),
            ],
            options={
                'ordering': ('-pub_date',),
                'verbose_name': '\u043f\u043b\u0430\u0442\u0451\u0436',
                'verbose_name_plural': '\u043f\u043b\u0430\u0442\u0435\u0436\u0438',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Payments', verbose_name='\u041f\u043b\u0430\u0442\u0435\u0436'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set([('name', 'email', 'phone')]),
        ),
        migrations.AlterUniqueTogether(
            name='payments',
            unique_together=set([('shop_id', 'order_number')]),
        ),
    ]
