# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-13 08:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 13, 8, 58, 25, 229000, tzinfo=utc), verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u0438\u044f \u0437\u0430\u044f\u0432\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='performed_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 13, 8, 58, 25, 228000, tzinfo=utc), null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0435 \u0437\u0430\u043f\u0440\u043e\u0441\u0430'),
        ),
    ]
